---
- name: Removing AWS resoyrces
  hosts: localhost
  vars_files:
    - aws_access_key.yml
  vars:
    elb_name: webapp-lb
    aws_region: us-west-1

  tasks:
    - name: remove load balancer
      ec2_elb_lb:
        name: "{{ elb_name }}"
        state: absent
        region: "{{ aws_region }}"
        zones:
          - "{{ aws_region }}a"
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"

    - ansible.builtin.include_role:
        name: aws-ec2
      vars:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        aws_region: us-west-1
        ec2_key: webservers_key
        ec2_instance_count: 2
        security_group_name: webserver-sg
        tag_name: webserver
        state: remove
