---
  - name: Setting up web application on AWS EC2 instances
    hosts: all
    # remote_user: ec2-user
    #become: true
    # vars_files:
      # - aws_access_key.yml

    tasks:
      - ansible.builtin.include_role:
          name: webapp
          apply:
            become: true

      - ansible.builtin.include_role:
          name: aws-elb
        # vars:
          # aws_access_key: "{{ aws_access_key_id }}"
          # aws_secret_key: "{{ aws_secret_access_key }}"
