---
- name: Deploying AWS instances to serve a webapp
  hosts: all

  tasks:
    - amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
      register: vpc_info

    - name: Set vpc id fact
      ansible.builtin.set_fact:
         fact_ec2_vpc_subnet_id: "{{ vpc_info.vpcs[0].vpc_id }}"

    - name: setting up security group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "webservers network sg"
        vpc_id: "{{ fact_ec2_vpc_subnet_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # http
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # https
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: sg_info

    - ansible.builtin.set_fact:
        fact_ec2_security_group_id: "{{ sg_info.group_id }}"

    - name: create a new ec2 key pair, returns generated private key
      amazon.aws.ec2_key:
        name: "{{ ec2_key }}"
        region: "{{ aws_region }}"
      register: keypair

    - become: true
      lineinfile:
        dest: "/etc/hosts"
        line: "192.168.0.191	tower.almendra.local"
        state: present

    - awx.awx.credential:
        name: aws-ec2-priv-key
        organization: Default
        state: present
        credential_type: Machine
        inputs:
          username: ec2-user
          ssh_key_data: "{{ keypair.key.private_key }}"

    - name: provision ec2 on aws
      amazon.aws.ec2_instance:
        key_name: "{{ ec2_key }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_ami_id }}"
        wait: true
        name: "{{ tag_name }}"
        exact_count: "{{ ec2_instance_count }}"
        tags:
          name: "{{ tag_name }}"
        region: "{{ aws_region }}"
        security_group: "{{ fact_ec2_security_group_id }}"
      register: ec2
