---
- name: create a new ec2 key pair, returns generated private key
  amazon.aws.ec2_key:
    name: "{{ ec2_key }}"
    region: "{{ aws_region }}"
    # aws_access_key: "{{ aws_access_key }}"
    # aws_secret_key: "{{ aws_secret_key }}"
  register: keypair

- name: Ensure .ssh dir exists
  ansible.builtin.file:
    state: directory
    path: ~/.ssh

- name: Create key private file
  ansible.builtin.copy:
    content: "{{ keypair.key.private_key }}"
    dest: ~/.ssh/ec2_priv_key.pem
    mode: 0600
  when: '"key pair already exists" not in keypair.msg'

# - awx.awx.credential:
    # name: aws-ec2-priv-key
    # organization: Default
    # state: present
    # credential_type: Machine
    # inputs:
      # username: ec2-user
      # ssh_key_data: "{{ keypair.key.private_key }}"
    # controller_username: admin
    # controller_password: redhat
    # controller_host: http://tower.almendra.local
